In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as sts

In [17]:
Weather_df = pd.read_csv('../Resources/WeatherPy.csv')
Weather_df.head()

,Unnamed: 0,City,Country,Cloudiness,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,andenes,NO,0,12/10/2017,69,69.31,16.12,37.40,14.99
1,1,mount isa,AU,0,12/10/2017,15,-20.73,139.50,89.60,9.17
2,2,coquimbo,CL,20,12/10/2017,68,-29.95,-71.34,64.40,9.17
3,3,tawang,IN,0,12/10/2017,51,27.58,91.87,33.67,1.14
4,4,ahipara,NZ,44,12/10/2017,76,-35.17,173.17,69.98,3.49

In [6]:
Weather_df2 = Weather_df.rename({'Unnamed: 0': 'City_ID'}, axis='columns')
Weather_df2.head()

,ID,City,Country,Cloudiness,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,andenes,NO,0,12/10/2017,69,69.31,16.12,37.40,14.99
1,1,mount isa,AU,0,12/10/2017,15,-20.73,139.50,89.60,9.17
2,2,coquimbo,CL,20,12/10/2017,68,-29.95,-71.34,64.40,9.17
3,3,tawang,IN,0,12/10/2017,51,27.58,91.87,33.67,1.14
4,4,ahipara,NZ,44,12/10/2017,76,-35.17,173.17,69.98,3.49

In [7]:
del Weather_df2['index']

KeyError: 'index'

In [5]:
Weather_df.to_html('WeatherPy.html')
print(Weather_df)

     Unnamed: 0       City Country  Cloudiness        Date  Humidity    Lat  \
0             0    andenes      NO           0  12/10/2017        69  69.31
1             1  mount isa      AU           0  12/10/2017        15 -20.73
2             2   coquimbo      CL          20  12/10/2017        68 -29.95
3             3     tawang      IN           0  12/10/2017        51  27.58
4             4    ahipara      NZ          44  12/10/2017        76 -35.17
..          ...        ...     ...         ...         ...       ...    ...
528         528  tuatapere      NZ          68  12/10/2017       100 -46.13
529         529  sistranda      NO           0  12/10/2017        63  63.73
530         530        vao      NC          92  12/10/2017       100 -22.67
531         531   sisimiut      GL          80  12/10/2017        99  66.94
532         532   ucluelet      CA          75  12/10/2017        81  48.93

        Lng  Max Temp  Wind Speed
0     16.12     37.40       14.99
1    139.50     89.60        9.17
2    -71.34     64.40        9.17
3     91.87     33.67        1.14
4    173.17     69.98        3.49
..      ...       ...         ...
528  167.68     57.79       17.25
529    8.83     30.20       25.28
530  167.48     75.57        7.63
531  -53.67     22.47        8.41
532 -125.55     50.00       11.41

[533 rows x 10 columns]